apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: installscripts-tls
  namespace: installscripts
spec:
  dnsNames:
    - script.ryzen.me
  issuerRef:
    kind: ClusterIssuer
    name: dns-cluster
  secretName: installscripts-tls
